### ISSUE TITLE
Add LICENSE?

### ISSUE THREAD

**Issue by avamk** [Deleetdk/kirkegaard#87]
Hi! I just stumbled upon this repository after searching for a way to randomly add NAs into a R data frame. Your package does so many useful things! (including adding NAs)

But can you add a LICENSE to this package, such as GPLv3+? I'd love to be able to learn from your code, use it, and attribute you, but can do so without a LICENSE. Thanks!

**Comment by Deleetdk** [comment]
Somehow did not see this before now. I don't really care about the license stuff, use the code here for anything you want. I added the MIT license.

https://github.com/Deleetdk/kirkegaard/commit/c7f8705533dddec6a27965a0719d23e50502fb5e
