### ISSUE TITLE
Install fails on "Error: unable to load R code in package 'kirkegaard'"

### ISSUE THREAD

**Issue by sbibauw** [Deleetdk/kirkegaard#88]
First, thank you for making your code public :-)
I was trying to install your package, but the installation failed on "Error: unable to load R code in package 'kirkegaard'"
First:

    Error in loadNamespace(name) : there is no package called 'curry'

Then I installed `curry` from CRAN (version `0.1.1`), and I got this error on trying to install your package again:

     Error : 'set_defaults' is not an exported object from 'namespace:curry'

Has there been a change in the dependencies? Maybe it is another curry?

**Comment by jhaltiga** [comment]
manually delete old curry folder from library and reinstall from CRAN.

See if that works. I had similar complications but was able to remedy.

**Comment by Deleetdk** [comment]
The curry package has to be installed manually. The code I normally use is given in the README:

`purrr::map(c("thomasp85/curry", "rOpenGov/dkstat"), ~devtools::install_github(.))`

I don't normally have issues with this on linux. As @jhaltiga says above, reinstalling by deleting the package dir usually fixes odd errors like this.

**Comment by sbibauw** [comment]
> The curry package has to be installed manually. The code I normally use is given in the README:
> 
> `purrr::map(c("thomasp85/curry", "rOpenGov/dkstat"), ~devtools::install_github(.))`

Thanks! It did work immediately after installing it this way (I even didn't have to uninstall the previous `curry` install, just running this line was enough). 

Sorry I had not seen this line in the README.
